//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string a = "a";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string AssetObj_1 = "AssetObj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string AssetObj_2 = "AssetObj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string AssetObj_3 = "AssetObj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string AssetObj = "AssetObj";
    }
    public class Audio
    {
        public const string BundleName = "audio";
        public const string Boss_BGM = "Boss_BGM";
        public const string Fire = "Fire";
        public const string Power = "Power";
        public const string Effcet_Great = "Effcet_Great";
        public const string Effect_Boss_Warning = "Effect_Boss_Warning";
        public const string Effect_Gameover = "Effect_Gameover";
        public const string Effect_Missile_Warning = "Effect_Missile_Warning";
        public const string Explode_Bullet = "Explode_Bullet";
        public const string Explode_Plane = "Explode_Plane";
        public const string Get_Gold = "Get_Gold";
        public const string Get_Item = "Get_Item";
        public const string Get_Shield = "Get_Shield";
        public const string Lost_Item = "Lost_Item";
        public const string Player_0 = "Player_0";
        public const string Player_1 = "Player_1";
        public const string Player_2 = "Player_2";
        public const string UI_Loading = "UI_Loading";
        public const string UI_StartGame = "UI_StartGame";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string b = "b";
    }
    public class Battle_bgm_ogg
    {
        public const string BundleName = "battle_bgm_ogg";
        public const string Battle_BGM = "Battle_BGM";
    }
    public class Bullet_prefab
    {
        public const string BundleName = "bullet_prefab";
        public const string Bullet = "Bullet";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string c = "c";
    }
    public class Enemy_boss_0_png
    {
        public const string BundleName = "enemy_boss_0_png";
        public const string Enemy_Boss_0 = "Enemy_Boss_0";
    }
    public class Enemy_boss_1_png
    {
        public const string BundleName = "enemy_boss_1_png";
        public const string Enemy_Boss_1 = "Enemy_Boss_1";
    }
    public class Enemy_elites_0_png
    {
        public const string BundleName = "enemy_elites_0_png";
        public const string Enemy_Elites_0 = "Enemy_Elites_0";
    }
    public class Enemy_elites_1_png
    {
        public const string BundleName = "enemy_elites_1_png";
        public const string Enemy_Elites_1 = "Enemy_Elites_1";
    }
    public class Enemy_elites_2_png
    {
        public const string BundleName = "enemy_elites_2_png";
        public const string Enemy_Elites_2 = "Enemy_Elites_2";
    }
    public class Enemy_item_0_png
    {
        public const string BundleName = "enemy_item_0_png";
        public const string Enemy_Item_0 = "Enemy_Item_0";
    }
    public class Enemy_item_1_png
    {
        public const string BundleName = "enemy_item_1_png";
        public const string Enemy_Item_1 = "Enemy_Item_1";
    }
    public class Enemy_normal_0_png
    {
        public const string BundleName = "enemy_normal_0_png";
        public const string Enemy_Normal_0 = "Enemy_Normal_0";
    }
    public class Enemy_normal_1_png
    {
        public const string BundleName = "enemy_normal_1_png";
        public const string Enemy_Normal_1 = "Enemy_Normal_1";
    }
    public class Enemy_normal_2_png
    {
        public const string BundleName = "enemy_normal_2_png";
        public const string Enemy_Normal_2 = "Enemy_Normal_2";
    }
    public class Enemy_normal_3_png
    {
        public const string BundleName = "enemy_normal_3_png";
        public const string Enemy_Normal_3 = "Enemy_Normal_3";
    }
    public class Enemy_normal_4_png
    {
        public const string BundleName = "enemy_normal_4_png";
        public const string Enemy_Normal_4 = "Enemy_Normal_4";
    }
    public class Enemy_normal_5_png
    {
        public const string BundleName = "enemy_normal_5_png";
        public const string Enemy_Normal_5 = "Enemy_Normal_5";
    }
    public class Game_bgm_ogg
    {
        public const string BundleName = "game_bgm_ogg";
        public const string Game_BGM = "Game_BGM";
    }
    public class Gamepanel_prefab
    {
        public const string BundleName = "gamepanel_prefab";
        public const string GamePanel = "GamePanel";
    }
    public class Gameroot_prefab
    {
        public const string BundleName = "gameroot_prefab";
        public const string GameRoot = "GameRoot";
    }
    public class Gameui_prefab
    {
        public const string BundleName = "gameui_prefab";
        public const string GameUI = "GameUI";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string ImagePrefabA = "ImagePrefabA";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string ImagePrefabB = "ImagePrefabB";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string ImagePrefabC = "ImagePrefabC";
    }
    public class Levelselectable_prefab
    {
        public const string BundleName = "levelselectable_prefab";
        public const string LevelSelectable = "LevelSelectable";
    }
    public class Loadingpanel_prefab
    {
        public const string BundleName = "loadingpanel_prefab";
        public const string LoadingPanel = "LoadingPanel";
    }
    public class Mapctrl_prefab
    {
        public const string BundleName = "mapctrl_prefab";
        public const string MapCtrl = "MapCtrl";
    }
    public class Plane_prefab
    {
        public const string BundleName = "plane_prefab";
        public const string Plane = "Plane";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SceneRes = "SceneRes";
    }
    public class Selectheropanel_prefab
    {
        public const string BundleName = "selectheropanel_prefab";
        public const string SelectHeroPanel = "SelectHeroPanel";
    }
    public class Selectlevelpanel_prefab
    {
        public const string BundleName = "selectlevelpanel_prefab";
        public const string SelectLevelPanel = "SelectLevelPanel";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string spriteatlas = "spriteatlas";
    }
    public class Squarea_prefab
    {
        public const string BundleName = "squarea_prefab";
        public const string SquareA = "SquareA";
    }
    public class Startgamepanel_prefab
    {
        public const string BundleName = "startgamepanel_prefab";
        public const string StartGamePanel = "StartGamePanel";
    }
    public class Strengthenpanel_prefab
    {
        public const string BundleName = "strengthenpanel_prefab";
        public const string StrengthenPanel = "StrengthenPanel";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TextureExample1 = "TextureExample1";
    }
    public class Ui_clickbutton_ogg
    {
        public const string BundleName = "ui_clickbutton_ogg";
        public const string UI_ClickButton = "UI_ClickButton";
    }
    public class Uibasicpanel_prefab
    {
        public const string BundleName = "uibasicpanel_prefab";
        public const string UIBasicPanel = "UIBasicPanel";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMultiPanel = "UIMultiPanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPanelWithImagePrefab = "UIPanelWithImagePrefab";
    }
    public class Uistackpanel1_prefab
    {
        public const string BundleName = "uistackpanel1_prefab";
        public const string UIStackPanel1 = "UIStackPanel1";
    }
    public class Uistackpanel2_prefab
    {
        public const string BundleName = "uistackpanel2_prefab";
        public const string UIStackPanel2 = "UIStackPanel2";
    }
}
